site_name: devrel.ai 
theme:
  name: material 
  custom_dir: overrides

# Add custom CSS
extra_css:
  - css/styles.css

# Analytics
extra:
  analytics:
    provider: custom

# Customizing navigation
nav_style: light


nav:
  - Home: index.md
  - Docs: docs/index.md
  - People: people/index.md
  - About: about/index.md

# Site metadata
site_description: DevRel.ai - Developer Relations in the Age of AI
site_author: Greg Baugues
