site_name: devrel.ai 
theme:
  name: material 

# Add custom CSS
extra_css:
  - css/styles.css

# Customizing navigation
nav_style: light


nav:
  - Home: index.md
  - Docs: docs/index.md
  - About: about.md

# Site metadata
site_description: DevRel.ai - Developer Relations in the Age of AI
site_author: Greg Baugues
